### ISSUE TITLE
`duqtools.log` contains escape sequences

### ISSUE THREAD

**Issue by stefsmeets** [CarbonCollective/fusion-dUQtools#201]
@v1kko I think these are the click color codes. For example:

```
INFO:operations:
INFO:operations:[31m[1mOperations in the Queue:[0m
INFO:operations:[31m========================[0m
INFO:operations:- [32mWriting out[0m : duqtools.yaml config file
INFO:duqtools.operations:[31m[1mApplying Operations[0m
INFO:duqtools.operations:[32mWriting out[0m : duqtools.yaml config file
```

**Comment by v1kko** [comment]
I noticed that as well, those are the ansi escape sequences that give the nice colors through click indeed. I actually liked them because if you head/tail/cat the log then the colors appear again.
But we can add an extra handler to the FileHandler  of the logging which solves this: 
https://stackoverflow.com/questions/48782529/exclude-ansi-escape-sequences-from-output-log-file (second answer)

**Comment by stefsmeets** [comment]
> I actually liked them because if you head/tail/cat the log then the colors appear again.

Ah, I didn't realize this was possible. In the terminal on the Gateway, when I cat/tail/head the logs  it does not show the colors.
