### ISSUE TITLE
Runs do not necessarily have the same timestepping or the same radial grid

### ISSUE THREAD

**Issue by v1kko** [CarbonCollective/fusion-dUQtools#97]
That can be a problem when comparing different runs. Or even in the same swarm due to dynamic timestepping

There are tools in the scripts (compare_im_runs.py) that try to fix this issue

**Comment by aaronkho** [comment]
In principle, we would like the user to be able to choose which entry acts as the base vector onto which the other runs are interpolated. This is done in `compare_im_runs.py` by assigning the first entry as the grid basis and the user can specify which one is first. I do not know if this ideology would transfer well into your framework.

Also, the tools in the `scripts` directory are also generalized to allow comparison of JINTRAC IDS inputs against JINTRAC IDS outputs. This adds an additional challenge as the inputs may only have one time slice, and thus often needs to be extrapolated in time (instead of interpolated). In this case, it is best to duplicate the closest time slice in the IDS, rather than do a linear extrapolation.

**Comment by stefsmeets** [comment]
> In principle, we would like the user to be able to choose which entry acts as the base vector onto which the other runs are interpolated. This is done in `compare_im_runs.py` by assigning the first entry as the grid basis and the user can specify which one is first. I do not know if this ideology would transfer well into your framework.

I think this makes sense. I just finished implementing a function to put all data on a common time basis in #164. The implementation is quite different, but the idea is the same. In the dashboard you will be able to pick any IMAS handle to serve as the time basis.

> In this case, it is best to duplicate the closest time slice in the IDS, rather than do a linear extrapolation.

I think that is this bit?
https://github.com/CarbonCollective/fusion-dUQtools/blob/7de9d6e28ae2d1a56c18f18bbba7e51e46ab4c17/scripts/compare_im_runs.py#L444-L448

**Comment by stefsmeets** [comment]
Implemented via:

- `duqtools.ids.rebase_on_ids`
- `duqtools.ids.rebase_on_time`

(See dashboard for example implementation)

**Comment by stefsmeets** [comment]
This can be closed now that we have a working implementation.
